# Spanish config file

[link]
copyMsg = "Â¡URL copiada correctamente!"

[link.here]
start = "AquÃ­"
middle = "aquÃ­"
end = "aquÃ­."

[link.go]
start = "Ir"
middle = "ir"
end = "ir."



[view]
exclamationBefore = "Â¡"
exclamationAfter = "!"
title = "Para"



[song]
title = "Canciones"



[qr]
title = "Codigo QR"



[index]
title = "Crear"
legend = "Â¡Crea tu propio sobre de celebraciÃ³n!"
visitToast = "Eres nuevo? Revisa el manual de uso"

[index.greeting]
label = "FelicitaciÃ³n ğŸ‘‹"
placeholder = "Ingresar felicitaciÃ³n"
content = "Feliz cumpleaÃ±os"
help = "Puede tener 25 caracteres y contener caracteres latinos y numÃ©ricos, guiones bajos y espacios"

[index.name]
label = "Nombre del receptor ğŸ§‘"
placeholder = "Ingresar nombre"
help = "Puede tener 50 caracteres y contener caracteres latinos y numÃ©ricos, guiones bajos y espacios"

[index.message]
label = "Mensaje ğŸ’Œ"
placeholder = "Ingresar mensaje"
content = "Te deseo un feliz cumpleaÃ±os y te deseo muchos aÃ±os mÃ¡s de vida"
help = "Puede tener 250 caracteres y contener caracteres latinos y numÃ©ricos, guiones bajos y espacios"

[index.songURL]
label = "CanciÃ³n ğŸ§ğŸ¶"
placeholder = "Ingresar URL"
help = [
    "El archivo tiene que ser mpeg (mp3, m4a, acc, mpga).",
    "La URL tiene que ser un enlace de descarga. MÃ¡s informaciÃ³n sobre cÃ³mo generar enlaces de descarga",
    "TambiÃ©n puedes encontrar enlaces prehechos",
]

[index.confConfig]
help = "Decora la pÃ¡gina con confeti, cambia el estilo, colores y tipo"

[index.confConfig.style]
label = "Estilo de confeti ğŸ‰"
options = [
    "Ninguno",
    "Lluvia",
    "Duchas ğŸ“µ",
    "Salto",
    "Poppers ğŸ“µ",
    "Flote (PrÃ³ximamente)",
]
optGroups = ["Bajan", "Suben", "Otros"]

[index.confConfig.type]
label = "Tipo de confeti ğŸŠ"
options = [
    "Confeti ğŸ‰",
    "Birrete de graduaciÃ³n ğŸ“",
    "Regalo ğŸ",
    "CorazÃ³n â¤ï¸",
    "Adorno navideÃ±o â„ï¸",
    "Calabaza de Halloween ğŸƒ",
    "Vacafeti ğŸ®",
    "Luvia de Hormigas ğŸŒ§ï¸"
]
optGroups = ["Regular", "Festivo", "???"]

[index.confConfig.color]
remove = "Quitar Color"

[index.submit]
create = "Crear"
generateQR = "Generar QR"

[index.qr]
title = "QR"
send = "Â¡Comparte este Codigo QR como regalo!"

[index.song]
title = "CanciÃ³nes"


[manual]
title = "Manual"